const containerProps = {
  width: 100,
  widthMode: "px",
  height: 100,
  heightMode: "px",
  display: "block",
  position: "static",
  top: 0,
  left: 0,
  right: 0,
  bottom: 0,
  flexDirection: "row",
  justifyContent: "flex-start",
  alignItems: "flex-start",
  grow: 0,
  shrink: 0,
  marginTop: 0,
  marginBottom: 0,
  marginRight: 0,
  marginLeft: 0,
  paddingTop: 0,
  paddingBottom: 0,
  paddingRight: 0,
  paddingLeft: 0,
  backgroundColor: "transparent",
  backgroundImage: "none",
  borderWidth: 0,
  borderStyle: "none",
  borderColor: "transparent",
  borderRadius: 0,
  borderTop: true,
  borderBottom: true,
  borderLeft: true,
  borderRight: true,
};

export default containerProps;
