const ImageProps = {
  src: "https://cdn4.iconfinder.com/data/icons/ionicons/512/icon-image-512.png",
  width: 100,
  widthMode: "px",
  height: 100,
  heightMode: "px",
  display: "block",
  position: "static",
  top: 0,
  left: 0,
  right: 0,
  bottom: 0,
  flexDirection: "row",
  justifyContent: "flex-start",
  alignItems: "flex-start",
  grow: 0,
  shrink: 0,
  fitMode: "Fill",
  repeatMode: "Repeat",
  marginTop: 0,
  marginBottom: 0,
  marginRight: 0,
  marginLeft: 0,
};

export default ImageProps;
